apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: nagp-assignment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres

        image: postgres:16

        env:
        - name: POSTGRES_DB
          value: nagpdb

        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD

        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: postgres-init-script
          subPath: init.sql

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-init-script
        configMap:
          name: postgres-init-script
